name: VHDLref
url: https://nobodywasishere.github.io
baseurl:

exclude: [cordova, documents, license.html, TODO.md, README.md, Makefile, test.html]

collections:
  refs:
    output: true

version: 1.0
